export const PLAYER_NAME_MAX_LENGTH = 16;
export const ROOM_CODE_LENGTH = 6;
export const ROOM_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/** Trim a player name, cap it to the lobby limit, and provide the server fallback. */
export function normalizePlayerName(value: string | null | undefined): string {
  const trimmed = value?.trim() ?? '';
  return trimmed.slice(0, PLAYER_NAME_MAX_LENGTH) || 'Player';
}

/** Normalize user-entered room codes to the exact alphabet generated by the server. */
export function normalizeRoomCode(value: string): string {
  let normalized = '';

  for (const character of value.toUpperCase()) {
    if (ROOM_CODE_ALPHABET.includes(character)) {
      normalized += character;
      if (normalized.length === ROOM_CODE_LENGTH) break;
    }
  }

  return normalized;
}

/** Return true only for a complete, already-normalized custom-room code. */
export function isCompleteRoomCode(value: string): boolean {
  return value.length === ROOM_CODE_LENGTH
    && [...value].every((character) => ROOM_CODE_ALPHABET.includes(character));
}
