export const PLAYER_NAME_STORAGE_KEY = 'rocket-arena-name';
export const DEFAULT_PLAYER_NAME = 'Player';
export const MAX_PLAYER_NAME_LENGTH = 16;
export const ROOM_CODE_LENGTH = 6;

const ROOM_CODE_CHARACTER_PATTERN = /[A-HJ-NP-Z2-9]/g;

export interface PlayerNameStorage {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

/** Normalize a player name exactly as it will be sent to the server. */
export function normalizePlayerName(value: string | null | undefined): string {
  const trimmed = value?.trim() ?? '';
  return (trimmed || DEFAULT_PLAYER_NAME).slice(0, MAX_PLAYER_NAME_LENGTH);
}

/**
 * Prefer a mounted input value, but retain the cached name when the input is absent.
 * This distinction prevents a screen transition from replacing a valid name with
 * the default merely because the main-menu input is no longer in the DOM.
 */
export function resolvePlayerName(
  inputValue: string | undefined,
  cachedName: string | null | undefined,
): string {
  return inputValue === undefined
    ? normalizePlayerName(cachedName)
    : normalizePlayerName(inputValue);
}

export function loadPlayerName(storage: PlayerNameStorage): string {
  try {
    return normalizePlayerName(storage.getItem(PLAYER_NAME_STORAGE_KEY));
  } catch {
    return DEFAULT_PLAYER_NAME;
  }
}

export function savePlayerName(storage: PlayerNameStorage, value: string): string {
  const normalized = normalizePlayerName(value);

  try {
    storage.setItem(PLAYER_NAME_STORAGE_KEY, normalized);
  } catch {
    // The in-memory value still works when storage is unavailable or blocked.
  }

  return normalized;
}

/** Keep only the unambiguous characters generated by the custom-room server. */
export function normalizeRoomCode(value: string): string {
  const characters = value.toUpperCase().match(ROOM_CODE_CHARACTER_PATTERN) ?? [];
  return characters.join('').slice(0, ROOM_CODE_LENGTH);
}

export function getRoomCodeValidationMessage(code: string): string | null {
  if (code.length === 0) return 'Enter a room code.';
  if (code.length !== ROOM_CODE_LENGTH) return `Room code must be ${ROOM_CODE_LENGTH} characters.`;
  return null;
}

export interface AcceptedLobbyCar {
  readonly sessionId: string;
  readonly team: 'blue' | 'orange';
  readonly name: string;
  readonly isHost: boolean;
}

export interface AcceptedLobbySnapshot {
  readonly phase: string;
  readonly totalCapacity: number;
  readonly cars: readonly Readonly<AcceptedLobbyCar>[];
}

export interface LobbyCarView extends AcceptedLobbyCar {
  readonly isLocal: boolean;
}

export interface AcceptedLobbyView {
  readonly phase: string;
  readonly totalCapacity: number;
  readonly totalCount: number;
  readonly cars: readonly Readonly<LobbyCarView>[];
  readonly blueCars: readonly Readonly<LobbyCarView>[];
  readonly orangeCars: readonly Readonly<LobbyCarView>[];
  readonly localIsHost: boolean;
  readonly matchStarting: boolean;
  readonly enterGameplay: boolean;
}

/** Project only decoder-accepted snapshots into lobby rendering/navigation state. */
export function createAcceptedLobbyView(
  snapshot: Readonly<AcceptedLobbySnapshot>,
  localSessionId: string,
): Readonly<AcceptedLobbyView> {
  const cars = Object.freeze(snapshot.cars.map((car) => Object.freeze({
    ...car,
    isLocal: car.sessionId === localSessionId,
  })));
  return Object.freeze({
    phase: snapshot.phase,
    totalCapacity: snapshot.totalCapacity,
    totalCount: cars.length,
    cars,
    blueCars: Object.freeze(cars.filter((car) => car.team === 'blue')),
    orangeCars: Object.freeze(cars.filter((car) => car.team === 'orange')),
    localIsHost: cars.some((car) => car.isLocal && car.isHost),
    matchStarting: snapshot.phase === 'countdown',
    enterGameplay: snapshot.phase === 'playing' || snapshot.phase === 'overtime',
  });
}