export const PLAYER_NAME_STORAGE_KEY = 'rocket-arena-name';
export const DEFAULT_PLAYER_NAME = 'Player';
export const MAX_PLAYER_NAME_LENGTH = 16;
export const ROOM_CODE_LENGTH = 6;

const ROOM_CODE_CHARACTER_PATTERN = /[A-HJ-NP-Z2-9]/g;

export interface PlayerNameStorage {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
}

/** Normalize a player name exactly as it will be sent to the server. */
export function normalizePlayerName(value: string | null | undefined): string {
  const trimmed = value?.trim() ?? '';
  return (trimmed || DEFAULT_PLAYER_NAME).slice(0, MAX_PLAYER_NAME_LENGTH);
}

/**
 * Prefer a mounted input value, but retain the cached name when the input is absent.
 * This distinction prevents a screen transition from replacing a valid name with
 * the default merely because the main-menu input is no longer in the DOM.
 */
export function resolvePlayerName(
  inputValue: string | undefined,
  cachedName: string | null | undefined,
): string {
  return inputValue === undefined
    ? normalizePlayerName(cachedName)
    : normalizePlayerName(inputValue);
}

export function loadPlayerName(storage: PlayerNameStorage): string {
  try {
    return normalizePlayerName(storage.getItem(PLAYER_NAME_STORAGE_KEY));
  } catch {
    return DEFAULT_PLAYER_NAME;
  }
}

export function savePlayerName(storage: PlayerNameStorage, value: string): string {
  const normalized = normalizePlayerName(value);

  try {
    storage.setItem(PLAYER_NAME_STORAGE_KEY, normalized);
  } catch {
    // The in-memory value still works when storage is unavailable or blocked.
  }

  return normalized;
}

/** Keep only the unambiguous characters generated by the custom-room server. */
export function normalizeRoomCode(value: string): string {
  const characters = value.toUpperCase().match(ROOM_CODE_CHARACTER_PATTERN) ?? [];
  return characters.join('').slice(0, ROOM_CODE_LENGTH);
}

export function getRoomCodeValidationMessage(code: string): string | null {
  if (code.length === 0) return 'Enter a room code.';
  if (code.length !== ROOM_CODE_LENGTH) return `Room code must be ${ROOM_CODE_LENGTH} characters.`;
  return null;
}
