/**
 * Procedural presentation tuning.
 * Ratios derive from authoritative CAR, BALL, and ARENA dimensions so visuals
 * can evolve without silently changing collision scale.
 */
export const VISUAL = {
  /** Shared night-stadium palette. Numeric colors are Three.js hex values. */
  PALETTE: {
    SKY: 0x04070d,
    FOG: 0x09111c,
    FIELD_BASE: 0x101923,
    FIELD_BLUE: 0x143551,
    FIELD_ORANGE: 0x4a2817,
    FIELD_LINE: 0xc6d7df,
    STRUCTURE_DARK: 0x111821,
    STRUCTURE_MID: 0x27323c,
    STRUCTURE_LIGHT: 0x798894,
    NEUTRAL_METAL: 0x303a43,
    RUBBER: 0x090b0e,
    GLASS: 0x78a9ba,
    BLUE: 0x2f78ff,
    BLUE_LIGHT: 0x66b7ff,
    ORANGE: 0xff6a2a,
    ORANGE_LIGHT: 0xffb05d,
    BALL_SHELL: 0xc5cbd0,
    BALL_PANEL_DARK: 0x46515a,
    BALL_CORE: 0x8ef2dc,
    WHITE_LIGHT: 0xe9f4f6,
    WARM_LIGHT: 0xffd7a1,
  },

  /** Original low-profile rocket-car proportions, expressed against CAR.BODY. */
  CAR: {
    SHELL: {
      REAR_WIDTH_RATIO: 0.94,
      SHOULDER_WIDTH_RATIO: 1,
      MID_WIDTH_RATIO: 0.93,
      NOSE_WIDTH_RATIO: 0.76,
      BELLY_Y_RATIO: -0.33,
      REAR_DECK_Y_RATIO: 0.08,
      SHOULDER_Y_RATIO: 0.3,
      MID_DECK_Y_RATIO: 0.23,
      NOSE_Y_RATIO: -0.04,
      REAR_Z_RATIO: -0.5,
      SHOULDER_Z_RATIO: -0.3,
      MID_Z_RATIO: 0.16,
      NOSE_Z_RATIO: 0.5,
      PANEL_INSET_RATIO: 0.018,
    },
    CANOPY: {
      WIDTH_RATIO: 0.58,
      HEIGHT_RATIO: 0.38,
      LENGTH_RATIO: 0.42,
      Z_OFFSET_RATIO: -0.04,
      BASE_Y_RATIO: 0.2,
      REAR_WIDTH_RATIO: 0.9,
      FRONT_WIDTH_RATIO: 0.72,
      REAR_HEIGHT_RATIO: 0.88,
      FRONT_HEIGHT_RATIO: 0.48,
    },
    WHEEL: {
      RADIUS_HEIGHT_RATIO: 0.34,
      WIDTH_BODY_RATIO: 0.14,
      X_OFFSET_WIDTH_RATIO: 0.51,
      FRONT_Z_LENGTH_RATIO: 0.31,
      REAR_Z_LENGTH_RATIO: -0.32,
      RIM_RADIUS_RATIO: 0.63,
      HUB_RADIUS_RATIO: 0.22,
      FENDER_RADIUS_RATIO: 1.13,
      FENDER_TUBE_RATIO: 0.11,
      TIRE_RADIAL_SEGMENTS: 8,
      TIRE_TUBULAR_SEGMENTS: 18,
      RIM_SEGMENTS: 10,
    },
    AERO: {
      SPLITTER_WIDTH_RATIO: 0.82,
      SPLITTER_LENGTH_RATIO: 0.09,
      SKIRT_HEIGHT_RATIO: 0.09,
      SPOILER_WIDTH_RATIO: 0.82,
      SPOILER_HEIGHT_RATIO: 0.66,
      SPOILER_CHORD_RATIO: 0.09,
      DIFFUSER_WIDTH_RATIO: 0.7,
      DIFFUSER_FIN_COUNT: 4,
    },
    LIGHTS: {
      HEADLIGHT_WIDTH_RATIO: 0.16,
      HEADLIGHT_HEIGHT_RATIO: 0.08,
      HEADLIGHT_GLOW: 1.9,
      TAILLIGHT_GLOW: 1.6,
    },
    EXHAUST: {
      X_OFFSET_WIDTH_RATIO: 0.2,
      Y_OFFSET_HEIGHT_RATIO: -0.12,
      NOZZLE_RADIUS_HEIGHT_RATIO: 0.09,
      NOZZLE_LENGTH_RATIO: 0.11,
      FLAME_LENGTH_RATIO: 0.34,
      TRAIL_LENGTH_RATIO: 0.96,
      GLOW: 2.4,
    },
    MATERIAL: {
      BODY_ROUGHNESS: 0.28,
      BODY_METALNESS: 0.62,
      PANEL_ROUGHNESS: 0.4,
      GLASS_ROUGHNESS: 0.08,
      GLASS_METALNESS: 0.18,
      GLASS_OPACITY: 0.76,
    },
  },

  /** Mechanical arena-ball layering and restrained light treatment. */
  BALL: {
    SHELL_DETAIL: 2,
    PANEL_COLOR_VARIANTS: 4,
    SHELL_SCALE: 0.992,
    SEAM_SCALE: 1.001,
    SEAM_OPACITY: 0.52,
    NODE_COUNT: 12,
    NODE_RADIUS_RATIO: 0.065,
    NODE_HEIGHT_RATIO: 0.025,
    NODE_SURFACE_RATIO: 1.004,
    NODE_GLOW: 1.45,
    CORE_RADIUS_RATIO: 0.38,
    CORE_GLOW: 1.2,
    ROUGHNESS: 0.34,
    METALNESS: 0.58,
  },

  /**
   * Ball presentation response. Every value is a presentation-only tunable
   * applied to smoothed accepted velocity; none of it feeds simulation.
   */
  BALL_MOTION: {
    /** Smoothing rate for the presented ball speed, in reciprocal seconds. */
    SPEED_RESPONSE: 8,
    /** Speed that maps to the fullest presented response, in metres/second. */
    SPEED_FOR_MAX: 34,
    /** Upper bound on presented gyro spin, in radians/second. */
    GYRO_MAX_RATE: 6.5,
    /** Emissive pulse rate in radians/second and its relative amplitude. */
    PULSE_RATE: 5.2,
    PULSE_AMOUNT: 0.28,
    /** Speed at which the motion trail starts to appear, in metres/second. */
    TRAIL_MIN_SPEED: 7,
    TRAIL_RESPONSE: 9,
    TRAIL_MAX_OPACITY: 0.34,
    TRAIL_MAX_LENGTH_SCALE: 1.15,
    /** Distance at which a nearby car begins to raise the rim glow, in metres. */
    PROXIMITY_RADIUS: 7,
    PROXIMITY_RESPONSE: 10,
    PROXIMITY_MAX_OPACITY: 0.3,
  },

  /** Stadium geometry remains outside or coincident with authoritative colliders. */
  STADIUM: {
    FIELD: {
      SURFACE_DEPTH: 0.1,
      MARKING_HEIGHT: 0.012,
      LINE_WIDTH: 0.1,
      CENTER_RING_RADIUS: 5,
      CENTER_RING_THICKNESS: 0.12,
      GRID_SPACING: 5,
      GRID_OPACITY: 0.12,
      HALF_TINT_OPACITY: 0.48,
    },
    PERIMETER: {
      KICKBOARD_HEIGHT: 0.72,
      KICKBOARD_DEPTH: 0.12,
      UPPER_GLASS_OPACITY: 0.12,
      POST_SPACING: 5,
      POST_WIDTH: 0.1,
    },
    GOAL: {
      FRAME_DEPTH: 0.24,
      FRAME_THICKNESS: 0.18,
      TUNNEL_RIBS: 5,
      GRID_COLUMNS: 8,
      GRID_ROWS: 5,
      GRID_OPACITY: 0.34,
      AMBIENT_GLOW: 0.78,
    },
    STANDS: {
      SIDE_OFFSET: 4.4,
      END_OFFSET: 4.2,
      TIER_COUNT: 3,
      ROWS_PER_TIER: 4,
      SEATS_PER_SIDE: 34,
      SEATS_PER_END: 22,
      ROW_RISE: 0.56,
      ROW_DEPTH: 0.72,
      SEAT_WIDTH: 0.42,
      SEAT_HEIGHT: 0.24,
      SEAT_DEPTH: 0.2,
      CROWD_LIGHT_RATIO: 0.24,
    },
    STRUCTURE: {
      ARCH_COUNT: 7,
      ARCH_RADIUS_PADDING: 7.5,
      ARCH_TUBE_RADIUS: 0.16,
      TRUSS_SEGMENTS: 16,
      RING_HEIGHT: 15.5,
      CATWALK_WIDTH: 1.2,
      SUPPORT_SPACING: 7.5,
    },
    LIGHTS: {
      BANKS_PER_SIDE: 4,
      LAMPS_PER_BANK: 6,
      BANK_HEIGHT: 14.2,
      LAMP_SIZE: 0.28,
      PANEL_GLOW: 1.8,
    },
    SCOREBOARD: {
      WIDTH: 8.2,
      HEIGHT: 2.4,
      DEPTH: 0.35,
      LETTER_HEIGHT: 0.58,
      LETTER_STROKE: 0.09,
      Y: 13.2,
    },
    ATMOSPHERE: {
      PARTICLE_COUNT: 180,
      PARTICLE_MIN_Y: 5,
      PARTICLE_MAX_Y: 19,
      PARTICLE_OPACITY: 0.16,
    },
  },

  /** Frame-rate-independent camera response and speed framing. */
  CAMERA: {
    ORBIT_RADIUS_X: 16,
    ORBIT_RADIUS_Z: 24,
    ORBIT_HEIGHT: 12.5,
    ORBIT_RATE: 0.14,
    ORBIT_LOOK_HEIGHT: 1.8,
    FOLLOW_DISTANCE_MIN: 9.8,
    FOLLOW_DISTANCE_MAX: 14.2,
    HEIGHT_MIN: 3.8,
    HEIGHT_MAX: 5.4,
    LOOK_AHEAD_MIN: 4.6,
    LOOK_AHEAD_MAX: 8.6,
    POSITION_RESPONSE: 7.2,
    LOOK_RESPONSE: 9.5,
    YAW_RESPONSE: 11,
    FOV_MIN: 56,
    FOV_MAX: 68,
    FOV_RESPONSE: 5.2,
    SPEED_FOR_MAX: 34,
    TELEPORT_DISTANCE: 24,
  },

  /** Motion derived only from synchronized transforms, velocity, and boost values. */
  MOTION: {
    WHEEL_SPIN_RESPONSE: 18,
    STEER_RESPONSE: 10,
    STEER_MAX_ANGLE: 0.34,
    STEER_VELOCITY_THRESHOLD: 0.5,
    BOOST_DROP_THRESHOLD: 0.15,
    BOOST_MIN_SPEED: 6,
    BOOST_HOLD_SECONDS: 0.18,
    BOOST_FADE_RESPONSE: 14,
    FLAME_FLICKER_RATE: 26,
    FLAME_FLICKER_AMOUNT: 0.16,
    TRAIL_OPACITY: 0.44,
    TRAIL_SPEED_SCALE: 0.018,
  },

  /** Renderer and lighting budget for typical desktop integrated graphics. */
  RENDER: {
    MAX_PIXEL_RATIO: 1.75,
    EXPOSURE: 1.1,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 190,
    FOG_NEAR: 62,
    FOG_FAR: 138,
    SHADOW_MAP_SIZE: 2048,
    SHADOW_BIAS: -0.00008,
    KEY_INTENSITY: 2.35,
    HEMISPHERE_INTENSITY: 0.84,
    GOAL_LIGHT_INTENSITY: 11.5,
    GOAL_LIGHT_DISTANCE: 24,
    FILL_INTENSITY: 0.55,
  },
} as const;
